2016-09-06 21:36:08,025 INFO Starting
2016-09-06 21:36:08,042 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:36:14,917 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:36:14,935 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:36:35,174 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:36:55,432 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:37:15,726 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:37:35,994 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:37:56,731 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:38:16,960 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:38:37,167 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:38:57,817 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:39:18,429 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:39:38,550 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:39:58,812 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:40:19,022 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:40:39,276 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:40:59,438 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:41:19,641 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:41:39,900 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:42:00,153 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:42:20,361 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:42:40,511 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:43:00,717 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:43:20,967 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:43:41,195 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:44:01,430 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:44:21,682 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:44:41,986 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:45:02,256 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:45:22,501 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:45:42,662 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:46:02,827 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:46:23,091 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:46:43,327 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:47:03,466 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:47:23,654 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:47:44,248 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:48:04,385 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:48:24,586 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:48:44,845 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:49:05,420 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:49:26,013 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:49:46,169 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:50:06,391 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:50:26,700 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:50:46,920 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:51:07,149 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:51:27,390 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:51:47,647 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:52:07,974 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:52:28,197 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:52:48,362 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:53:08,701 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:53:28,921 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:53:49,076 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:09,288 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:17,308 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:24,713 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:24,713 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:31,602 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:31,618 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:35,372 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:40,760 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:54:41,172 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:55:01,407 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:55:21,664 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:55:41,960 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:56:02,214 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:56:22,439 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:56:42,677 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:57:02,929 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:57:23,131 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:57:43,736 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:58:03,906 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:58:24,193 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:58:44,436 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:59:05,100 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:59:25,705 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 21:59:45,961 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:00:06,125 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:00:26,323 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:00:46,631 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:01:06,870 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:01:27,121 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:01:47,321 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:02:00,805 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:02:00,814 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:02:21,424 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:02:42,091 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:03:02,417 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:03:22,639 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:03:42,900 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:04:03,065 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:04:23,264 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:04:43,591 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:05:03,832 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:05:24,140 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:05:44,378 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:06:04,535 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:06:24,689 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:06:44,902 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:07:05,041 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:07:25,227 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:07:46,612 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:08:07,201 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:08:27,877 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:08:48,154 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:09:08,771 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:09:29,438 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:09:49,668 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:10:09,873 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:10:30,038 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:10:50,181 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:11:10,338 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:11:30,558 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:11:50,684 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:12:10,940 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:12:31,200 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:12:51,413 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:13:12,060 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:13:32,259 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:13:52,946 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:14:13,177 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:14:33,384 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:14:53,683 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:15:14,608 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:15:35,110 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:15:44,931 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:15:44,969 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:16:05,170 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:16:25,867 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:16:46,335 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:17:06,882 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:17:27,188 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:17:47,943 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:18:08,332 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:18:28,888 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:18:49,112 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:19:09,798 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:19:30,436 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:19:51,169 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:20:11,371 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:20:31,574 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:20:52,773 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:21:13,166 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:21:33,530 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:21:53,686 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:22:13,889 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:22:34,859 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:22:56,148 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:23:16,446 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:23:37,584 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:23:58,456 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:24:18,686 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:24:39,040 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:24:59,753 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:25:20,315 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:25:41,019 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:26:01,236 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:26:22,196 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:26:44,378 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:27:09,733 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:27:30,044 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:27:52,459 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:28:13,304 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:28:34,197 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:28:55,982 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:29:23,942 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:29:45,051 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:30:08,463 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:30:30,371 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:30:50,731 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:31:10,956 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:31:31,185 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:31:51,428 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:32:12,808 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:32:33,066 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:32:53,341 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:33:13,893 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:33:35,023 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:33:56,143 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:34:22,709 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:34:43,928 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:35:06,085 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:35:26,537 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:35:47,785 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:36:08,303 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:36:34,211 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:36:56,223 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:37:18,085 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:37:38,774 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:38:00,045 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:38:21,012 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:38:42,666 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:39:02,837 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:39:23,527 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:39:44,203 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:40:04,483 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:40:24,675 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:40:44,912 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:41:05,106 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:41:25,420 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:41:45,624 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:42:05,809 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:42:26,578 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:42:47,939 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:43:08,283 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:43:28,605 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:43:48,818 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 22:44:13,935 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 23:44:38,441 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-06 23:44:38,522 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-06 23:44:59,292 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 00:34:18,959 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 00:34:18,991 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 00:35:47,499 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 00:35:47,506 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 00:36:07,812 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 01:36:34,753 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 01:36:34,779 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 01:36:55,547 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 01:37:15,796 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 01:37:36,454 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 01:37:56,673 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 01:38:16,991 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 02:38:44,110 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 02:38:44,146 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 02:39:04,793 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 03:39:32,124 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 03:39:32,160 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 03:39:52,861 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 04:10:37,587 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 04:10:37,621 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 04:10:58,450 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 05:33:07,167 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 05:33:07,200 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 05:33:27,902 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 06:33:54,258 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 06:33:54,279 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 06:34:15,035 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 07:34:42,804 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 07:34:42,829 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 07:35:03,514 INFO Starting new HTTPS connection (1): api.telegram.org
2016-09-07 08:29:17,420 ERROR HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
Traceback (most recent call last):
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/initd.py", line 87, in start
    run()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 64, in loop_callback
    start_telebot()
  File "/Users/Muna/Programming/ema/ema/telegram_bot/management/commands/emabot.py", line 56, in start_telebot
    bot.polling()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 192, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 215, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 122, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/__init__.py", line 92, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 139, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Muna/.virtualenvs/ema/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
2016-09-07 08:29:17,424 INFO Exiting.
